### ISSUE TITLE
算法代码使用说明

### ISSUE THREAD

**Issue by KenWang94** [ajex1988/blending#1]
您好 ，拜读了您的关于混合视频算法的论文，在代码运行方面需要您这边的具体操作，如视频的放置位置，输入输出等  

int main(int argc, char* argv[]) {
    const std::string script_file = RESOURCES_DIR "script.txt";
    const std::string mask_output_dir = APP_NAME "_masks/
您代码中 RESOURCES_DIR和APP_NAME如何选择

**Comment by jaimeyzzz** [comment]
1. RESOURCES_DIR is defined in Cmakelists.txt and is set to /your/path/resources/ as default for my example codes. You should put a png image sequence under the resource folder. Or you can set your own resource dir in the Cmakelists.txt file of different exmaple code directories. 

    For example, modify line 47 in /your/path//src/examples/mvc_blender_demo/CMakeLists.txt if you want to run mvc code with your own resource dir
```cmake
target_compile_definitions(${target}
    PRIVATE
    RESOURCES_DIR="${CMAKE_CURRENT_SOURCE_DIR}/../../../resources/"
)
```

2. APP_NAME is defined in example code for different examples. You do not need to set this. You can find a macro line in main.cc file like the following one

```c
#define APP_NAME "xxx"
```

I'm sorry that the documentation is not detailed enough. You are welcome to  email me if you feel confused about using the code. It's not so proper to comment this as an issue. 

I'm goint to close it and please feel free to email me about code usage.
