### ISSUE TITLE
confused about using the code

### ISSUE THREAD

**Issue by KenWang94** [ajex1988/blending#2]
Jiaming Lu 
       Hello, in the code running, I can't find MBB.Mask, you can tell me how to get MBB.Mask, and where it should be placed.
![image](https://user-images.githubusercontent.com/34003317/43497222-a3600d74-9573-11e8-9edc-535b84e39255.png)

 Did png you mentioned before refer to the following png?

![image](https://user-images.githubusercontent.com/34003317/43497229-aa53dc6e-9573-11e8-8b5b-4c2b527d2696.png)

Thank you for your help, I look forward to your reply as soon as possible.

**Comment by KenWang94** [comment]
I am sorry toisturb you in here,The email sent to you has not been answered.

**Comment by KenWang94** [comment]
I am sorry to disturb you in here,The email sent to you has not been answered.

**Comment by jaimeyzzz** [comment]
You can use remmaper_demo and find_seam_demo to generate this masks from a PTStitcher script file(provided under resources folder, you need to generate it by PTGui tool if you want to stitch your own images).
Sorry that the documentation is not so detailed, so I will add an example with all these mask images, origin images, script file and some tutorial within this week. 
By the way, I didn't get your email. You can email me ( loyaveforever@gmail.com ). I will reply soon on workdays.

**Comment by jaimeyzzz** [comment]
The resource files are uploaded now, you can get them by clicking the link in README.

**Comment by jaimeyzzz** [comment]
I will close this issue if you have no more questions.
